First stab through internal routing
foolswood/rage pull request #81
Opened 2018-07-12 14:56 UTC by foolswood

There's tidying to be done here, and almost certainly some sharp edge cases remaining.
That said it works in the basic "playing back a thing" case.

2018-07-12 17:23 UTC, ch3pjw requested changes
Some things to look at. I haven't quite got to the end of looking through `proc_block.c` as it's quite fiddly!

2018-07-12 17:23 UTC, ch3pjw commented on graph/src/proc_block.c
> +            rage_StepSet * const extended_deps = rage_step_set_add(deps[i.idx], i.step);
The set of dependencies should have the source's step, not the sink's.

2018-07-12 17:23 UTC, ch3pjw commented on graph/src/proc_block.c
> +        return RAGE_FAILURE_CAST(rage_Error, ops);
finish crit update in error case

2018-07-12 17:23 UTC, ch3pjw commented on graph/src/proc_block.c
> +            assigned_cons = c;
620 and 629 probably belong together?

2018-07-16 08:41 UTC, foolswood commented on graph/src/proc_block.c
> +                for (
rage_alloc_int_array?

2018-07-16 09:33 UTC, ch3pjw approved these changes
I think I kinda handwavily understand what this is doing!

2018-07-16 09:34 UTC, merged